### ISSUE TITLE
Create ReadMe File 

### ISSUE THREAD

**Issue by BajraYeJoon** [BajraYeJoon/JavaScript-DOM-projects#1]
-Create a readme file with simple description
-Include steps to fork and contribute 
-include gif or screenshot of the page

**Comment by oneamanish** [comment]
see my pull req.

**Comment by NgoQuocBao1010** [comment]
I can help you with this issue. Can you assign me for this?

**Comment by BajraYeJoon** [comment]
@NgoQuocBao1010  Yes you can do it. please make read me file more pleasing rather than just simple writing.
 (emoji can be added and screenshot of the page can be optional

**Comment by BajraYeJoon** [comment]
@NgoQuocBao1010  ...Awaiting Response
